#!/bin/bash
t1=$(( $(date +%s%N) / 1000000))
./randomtestcard1 > temp
t2=$(( $(date +%s%N) / 1000000))
Dt=$(( $t2 - $t1 ))
printf "\033[31mExecution Time $Dt miliseconds\033[0m\n"
printf "Execution Time $Dt miliseconds\n" > randomtestcard1.out
